# Generated by Django 5.2.16 on 2026-07-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookevent',
            name='message_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
